apiVersion: v1
kind: Secret
metadata:
  name: dso202-secret
  namespace: dso202-assignment-01
type: Opaque
stringData:
  DB_USER: "taskuser"
  DB_PASSWORD: "changeme-in-real-life"
  POSTGRES_USER: "taskuser"
  POSTGRES_PASSWORD: "changeme-in-real-life"
